development:
    adapter: sqlite3
    encoding: utf-8
    database: /home/milan/krasi/PlaceFinder/db/development.db

test:
    adapter: sqlite3
    encoding: utf-8
    database: /home/milan/krasi/PlaceFinder/db/test.db
