development:
    adapter: sqlite3
    encoding: utf-8
    database: /home/krasimira/Ruby/PlaceFinder/db/development.db

test:
    adapter: sqlite3
    encoding: utf-8
    database: /home/krasimira/Ruby/PlaceFinder/db/test.db
